name: statsverse_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - numpy>=1.25
  - pandas>=2.1
  - scipy>=1.12
  - matplotlib>=3.8
  - seaborn>=0.12
  - plotly>=6.1
  - scikit-learn>=1.3
  - statsmodels>=1.2
  - pillow>=10.1
  - notebook>=7.0
  - jupyterlab>=4.3
  - ipython>=8.15
  - tqdm>=4.66
  - pip
  - pip:
      - xgboost>=1.8
      - lightgbm>=4.4
      - catboost>=1.2
